build:
  tests:
    override:
      - pylint-run --rcfile=.pylintrc
      - py-scrutinizer-run
checks:
  python:
    code_rating: true
    duplicate_code: true
filter:
  excluded_paths:
    - "*/tests/*"
