docs_dir: docs-source
# in order to expose with github page project
site_dir: docs

# Project information
site_name: async-btree
site_url: https://geronimo-iia.github.io/async-btree/
site_description: Async behavior tree
site_author: Jerome Guibert

# Repository
repo_name: 'geronimo-iia/async-btree'
repo_url: 'https://github.com/geronimo-iia/async-btree'

# Copyright
copyright: 'Copyright © 2019 <a href="https://geronimo-iia.github.io/async-btree/">Jerome Guibert</a>'

# Configuration
theme:
  name: 'material'
  language: 'en'
  palette:
    primary: 'deep purple'
    accent: 'light-blue'
  font:
    text: 'Ubuntu'
    code: 'Ubuntu Mono'
  feature:
    tabs: false

nav:
- Home: README.md
- Async Btree API:
  - packages: async_btree/packages.md
  - definition: async_btree/definition.md
  - analyze: async_btree/analyze.md
  - control: async_btree/control.md
  - decorator: async_btree/decorator.md
  - leaf: async_btree/leaf.md
  - parallele: async_btree/parallele.md
  - utils: async_btree/utils.md
- About:
  - Contributing: contributing.md
  - Release Notes: CHANGELOG.md
  - License: LICENSE.md
  - Code of Conduct: CODE_OF_CONDUCT.md

# Customization
extra:
  social:
    - type: 'github'
      link: 'https://github.com/geronimo-iia'
    - type: 'twitter'
      link: 'https://twitter.com/schtroumphix'      


# Extensions
markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.codehilite:
      guess_lang: false
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - fontawesome_markdown